using UnityEngine;

public class UnitAdapter
{
    //Copy game state to DTO before Game Engine transfers object data into json file
    // public static UnitData ToData()
    // {
    //     return;
    // }
    
    //Read contents of json file generated by unity engine that returns an object
    //From UnitData Object to HexGridManager
    public static void FromData()
    {
        return;
    }
}